# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567924f316297fc290f61bc1cf2895f3326f137c192ca55b552bba322f74913b11e85719a08f8899576ab664e5f824071831c168e9bf50e430cd78041bf2229b

test:
  secret_key_base: 9ac54778ed8b1b0b762f0ee51259619ccc1ec87b049d58e6b30be8983d69aa717bd1e99f1c363f1b4945841d66713bf855f9e98bce71bc69cf0eb4a63ce08ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
